apiVersion: v1
kind: Service
metadata:
  name: bookstore-api
  namespace: bookstore-app
spec:
  selector:
    app: bookstore-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31676
  type: LoadBalancer

