apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api
  namespace: bookstore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-api
  template:
    metadata:
      labels:
        app: bookstore-api
    spec:
      containers:
      - name: bookstore-api
        image: bholcombe/bookstore-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bookstore-api-config
        - secretRef:
            name: bookstore-api-secrets

